language: objective-c
osx_image: xcode8.3
sudo: false
before_install:
- bundle install
- bundle exec pod repo update
- bundle exec pod install
before_script:
- ./.fastlane/add-key.sh
script:
- ./.fastlane/unittests.sh
- ./.fastlane/testflight.sh
env:
  global:
  - secure: "gQILHGdQKHCSfPiBtclAnrxRoiDmYGVrHy45A+t4G4NarOAd2dkccIqF3Hgnq915CMCEJ8oilLoAibsNeUAkZdfQv5/CYdEIFzhHbKLfaPkr5kDH47EPCIDMu+MaLADcoXyxCA9ZGM3Rz5jOrwbi8DsRDNdz8guLUH1DYk6GotrwSlq23GeUW631Ft8P8u0T2PdMMdS31m1SYr6jgcAI0hlX9+EOz+koDgozeEI5y/2AArqU0HMeXmor+cqjAx5/xIVu26+4voSKtFS1+QHAN+HqUyCs+v4FAUp1UCddY6hsQj+hYs59ADy43s7bhdvlIbfD7aEvfaVbqJZzBqzNmkXbfT0qAtUzQivZbmWF9YeYGNnx9L1n18rY80hIi3jtH0COGj1AgoFhdyQtwQpzWZBSrUf0cUh/kVdh+fTGfnXIZj1bc2w6YS3r/i1uwc+eCTGL6Ks1HMP+TQzLHGIlMdzpzD7FZG9EPXEyhMp9ckQ6OPAX2xeTmLlVkplLlbNRVwMspjV7P2BAJblPJl+/OL1GNWQqNsQDP4ZgHnYEKk0vca8q+mV96K0yTqvnQ7bbBxYhFstJrjr/uOCdg0rJKk5Xl0dEPCttKjoMRXyy4xjA3c0G+Z4bLGekzS6pM7xcYUUIryTHFxBp0fJ+4ylJYlLAd/M+zyJvY7WwdBRQjNg="
  - secure: "i53tKkfPNYN5jz4u6T9nREn7xiruOy3EFHEGNefkwu8NVtY8AzY1ep+RSsWubipQObmQ46BVjttoy09BPq9muDeWqw/np4dJfL8ZQCzyGsRGnNpplkstpDPLc4uFjpYk+2VE/ZK+4Ov6vUwFucJYcnGElsLZXBClYiQLkvJUZrE9Dw5TSCCD/GcWzhRjMcVstuq5FUi7r4L5UUviRciufufIbar5XIGqU/NFm7Z+wwq0ZTEa6LPg5f4VW9p9mmuqj/Rgk0Dfhl8tGWaNiSTzEtAY17i+e/WJDnbPMqLSETsmQ8PjAIBJMEfowLO8ZWBhPte9PWsmmrGlqxXuwxDUeJYTS6QicRNo7DygpwGTywgJ8czkKKYHhx+P86SquYfhexN8hIQFzusUWfHc7xrnvaJqkB/zU+XoFYsSfnLbXB8h8BU+Mby/gLLjTQdWUCQMyFOfmP6Go8XcGvtqARKk167hfWe5r0nYtCc0d+b7bN5X662nSKL6VZVa3WTYoxK5faIFg5V2dMS8u+KIIVdmHieC41Sa45i+ZszBZ0CrgSFf/LzJhKp7wb0TxvCP582Ff65Gt/XTbkFZkT8Bjme173oJ/+k2hwFuxLJoLkSFv/L6ISs9+LTOazi9NDbtndjNhEqv3re/LGbEjw1iZQMD+v8UCpeOIBOeQi+k9gInWyc="
